# Generated by Django 5.2.4 on 2025-07-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_ride_event', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=60)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id_ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_events', to='rides.ride')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
