# Generated by Django 5.2.4 on 2025-07-08 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en-route', 'En-route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='en-route', max_length=20)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('id_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('id_rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
